### ISSUE TITLE
Sub-process 4602 exited with code 0 and signal Segmentation fault

### ISSUE THREAD

**Issue by apduvuri** [dimitri/pgcopydb#797] opened 2024-06-03 09:09 UTC
Source version is 11 and 2vCores
Target version is 15.6 and 4vCores

Around 68130 tables and indexes

`pgcopydb queue copy worker log`

```bash
2024-05-30T12:53:48.078Z	prod_db	4604	catalog.c	DEBUG	            Catalog has been setup for source "postgres://adminuser%40migrapoc@migrapoc.postgres.database.azure.com:5432/prod_db", target "postgres://admintarget@test.postgres.database.azure.com:5432/prod_db", snapshot "00000010-0000014E-1"
2024-05-30T12:53:48.092Z	prod_db	4604	catalog.c	SQLite	           [SQLite] select name, fetched, duration from section where name = $1
2024-05-30T12:53:48.095Z	prod_db	4604	catalog.c	SQLite	           [SQLite] table-data-parts
2024-05-30T12:53:48.097Z	prod_db	4604	catalog.c	SQLite	           [SQLite] select count(t.oid) as count,        count(p.oid) as countSplits,        sum(p.partcount) as countParts,        sum(bytes) as totalBytes,        sum(reltuples) as totalTuples   from s_table t        left join          (             select oid, count(*) as partcount                from s_table_part            group by oid         ) p         on p.oid = t.oid
2024-05-30T12:53:48.192Z	prod_db	4604	catalog.c	SQLite	           [SQLite]   select t.oid, qname, nspname, relname, amname, restore_list_name,          relpages, reltuples, t.bytes, t.bytes_pretty,          exclude_data, part_key,          coalesce(p.partcount, 0) as partcount,          0 as partnum, 0 as min, 0 as max,          c.srcrowcount, c.srcsum, c.dstrowcount, c.dstsum,          sum(s.duration), sum(s.bytes)     from s_table t          left join s_table_part p on p.oid = t.oid          left join s_table_chksum c on c.oid = t.oid          left join summary s on s.tableoid = t.oid group by t.oid order by t.bytes desc
2024-05-31T23:09:29.782Z	prod_db	4604	catalog.c	ERROR	           Failed to iterate over list of tables, see above for details
2024-05-31T23:09:29.795Z	prod_db	4604	table-data.c	FATAL	         Failed to add tables to the COPY worker queue, terminating
2024-05-31T23:09:29.831Z	prod_db	4604	copydb.c	FATAL	             Terminating all processes in our process group
2024-05-31T23:09:29.846Z	prod_db	4604	copydb.c	DEBUG	             Waiting for sub-processes to finish
2024-05-31T23:09:29.846Z	prod_db	4604	copydb.c	DEBUG	             copydb_wait_for_subprocesses: no more children
2024-05-31T23:09:29.847Z	prod_db	4604	table-data.c	ERROR	         Failed to copy table data, see above for details
```

**Comment by dimitri** [comment] 2024-06-03 14:24
There is not enough information in the logs to fix the issue unfortunately. Can you share either the SQLite file or maybe the source database schema or see on your side if you can reproduce the issue and share how?

**Comment by apduvuri** [comment] 2024-06-04 10:05
sure 

> pgcopydb queue copy worker

```bash
2024-05-30T12:53:48.051Z	prod_db	4604	table-data.c	NOTICE	         Started queue tables COPY worker 4604 [4597]
2024-05-30T12:53:48.052Z	prod_db	4604	catalog.c	DEBUG	            Skipping opening SQLite database "/datadrive/migrations_data/bf789dd1-506b-4758-a32e-905d1fbcae1b/oid-657901/schema/source.db": already opened
2024-05-30T12:53:48.052Z	prod_db	4604	catalog.c	DEBUG	            Opening SQLite database "/datadrive/migrations_data/bf789dd1-506b-4758-a32e-905d1fbcae1b/oid-657901/schema/filter.db" with lib version 3.45.1
2024-05-30T12:53:48.054Z	prod_db	4604	catalog.c	DEBUG	            Opening SQLite database "/datadrive/migrations_data/bf789dd1-506b-4758-a32e-905d1fbcae1b/oid-657901/schema/target.db" with lib version 3.45.1
2024-05-30T12:53:48.073Z	prod_db	4604	catalog.c	SQLite	           [SQLite] select id, source_pg_uri, target_pg_uri, snapshot,        split_tables_larger_than, filters, plugin, slot_name   from setup
2024-05-30T12:53:48.078Z	prod_db	4604	catalog.c	DEBUG	            Catalog has been setup for source "postgres://adminuser%40migrapoc@migrapoc.postgres.database.azure.com:5432/prod_db", target "postgres://admintarget@test.postgres.database.azure.com:5432/prod_db", snapshot "00000010-0000014E-1"
2024-05-30T12:53:48.092Z	prod_db	4604	catalog.c	SQLite	           [SQLite] select name, fetched, duration from section where name = $1
2024-05-30T12:53:48.095Z	prod_db	4604	catalog.c	SQLite	           [SQLite] table-data-parts
2024-05-30T12:53:48.097Z	prod_db	4604	catalog.c	SQLite	           [SQLite] select count(t.oid) as count,        count(p.oid) as countSplits,        sum(p.partcount) as countParts,        sum(bytes) as totalBytes,        sum(reltuples) as totalTuples   from s_table t        left join          (             select oid, count(*) as partcount                from s_table_part            group by oid         ) p         on p.oid = t.oid
2024-05-30T12:53:48.192Z	prod_db	4604	catalog.c	SQLite	           [SQLite]   select t.oid, qname, nspname, relname, amname, restore_list_name,          relpages, reltuples, t.bytes, t.bytes_pretty,          exclude_data, part_key,          coalesce(p.partcount, 0) as partcount,          0 as partnum, 0 as min, 0 as max,          c.srcrowcount, c.srcsum, c.dstrowcount, c.dstsum,          sum(s.duration), sum(s.bytes)     from s_table t          left join s_table_part p on p.oid = t.oid          left join s_table_chksum c on c.oid = t.oid          left join summary s on s.tableoid = t.oid group by t.oid order by t.bytes desc
2024-05-31T23:09:29.782Z	prod_db	4604	catalog.c	ERROR	           Failed to iterate over list of tables, see above for details
2024-05-31T23:09:29.795Z	prod_db	4604	table-data.c	FATAL	         Failed to add tables to the COPY worker queue, terminating
2024-05-31T23:09:29.831Z	prod_db	4604	copydb.c	FATAL	             Terminating all processes in our process group
2024-05-31T23:09:29.846Z	prod_db	4604	copydb.c	DEBUG	             Waiting for sub-processes to finish
2024-05-31T23:09:29.846Z	prod_db	4604	copydb.c	DEBUG	             copydb_wait_for_subprocesses: no more children
2024-05-31T23:09:29.847Z	prod_db	4604	table-data.c	ERROR	         Failed to copy table data, see above for details
```

> pgcopydb copy supervisor

```bash
2024-05-30T12:53:48.024Z	prod_db	4597	table-data.c	NOTICE	         Started COPY supervisor 4597 [4157]
2024-05-30T12:53:48.024Z	prod_db	4597	copydb.c	TRACE	             copydb_register_sysv_queue[6]: 2
2024-05-30T12:53:48.025Z	prod_db	4597	queue_utils.c	DEBUG	         Created message copy table-data queue 2 (cleanup with `ipcrm -q 2`)
2024-05-30T12:53:48.026Z	prod_db	4597	table-data.c	INFO	         STEP 4: starting 4 table-data COPY processes
2024-05-30T12:53:48.030Z	prod_db	4597	catalog.c	DEBUG	            Opening SQLite database "/datadrive/migrations_data/bf789dd1-506b-4758-a32e-905d1fbcae1b/oid-657901/schema/source.db" with lib version 3.45.1
2024-05-30T12:53:48.038Z	prod_db	4597	catalog.c	SQLite	           [SQLite] insert or replace into timings(id, label, start_time_epoch)values($1, $2, $3)
2024-05-30T12:53:48.042Z	prod_db	4597	catalog.c	SQLite	           [SQLite] 5, COPY (cumulative), 1717073628
2024-05-30T12:53:48.051Z	prod_db	4597	copydb.c	DEBUG	             Waiting for sub-processes to finish
2024-05-31T23:09:29.781Z	prod_db	4597	copydb.c	ERROR	             Sub-process 4602 exited with code 0 and signal Segmentation fault
2024-05-31T23:09:29.781Z	prod_db	4597	copydb.c	ERROR	             Signaling other processes to terminate (see --fail-fast)
2024-05-31T23:09:29.781Z	prod_db	4597	copydb.c	FATAL	             Terminating all processes in our process group
2024-05-31T23:09:29.795Z	prod_db	4597	copydb.c	DEBUG	             Waiting for sub-processes to finish
2024-05-31T23:09:29.920Z	prod_db	4597	copydb.c	ERROR	             Sub-process 4600 exited with code 12
2024-05-31T23:09:29.920Z	prod_db	4597	copydb.c	ERROR	             Sub-process 4601 exited with code 12
2024-05-31T23:09:29.920Z	prod_db	4597	copydb.c	ERROR	             Sub-process 4603 exited with code 12
2024-05-31T23:09:29.920Z	prod_db	4597	copydb.c	ERROR	             Sub-process 4604 exited with code 12
2024-05-31T23:09:29.921Z	prod_db	4597	copydb.c	DEBUG	             copydb_wait_for_subprocesses: no more children
2024-05-31T23:09:29.921Z	prod_db	4597	copydb.c	DEBUG	             copydb_wait_for_subprocesses: no more children
2024-05-31T23:09:29.921Z	prod_db	4597	table-data.c	ERROR	         Some COPY worker process(es) have exited with error, see above for details
2024-05-31T23:09:29.921Z	prod_db	4597	copydb.c	FATAL	             Terminating all processes in our process group
2024-05-31T23:09:29.922Z	prod_db	4597	copydb.c	DEBUG	             Waiting for sub-processes to finish
2024-05-31T23:09:29.922Z	prod_db	4597	copydb.c	DEBUG	             copydb_wait_for_subprocesses: no more children
2024-05-31T23:09:29.922Z	prod_db	4597	table-data.c	ERROR	         Failed to copy table data, see above for details
2024-05-31T23:09:29.923Z	prod_db	4597	queue_utils.c	DEBUG	         iprm -q 2 (copy table-data)
```
Further no errors were found in `pgcopydb copy worker` with process id 4602

**Comment by dimitri** [comment] 2024-06-04 12:10
What requires our attention is the following:

```
2024-05-31T23:09:29.781Z	prod_db	4597	copydb.c	ERROR	             Sub-process 4602 exited with code 0 and signal Segmentation fault
```

Do you have a core file that we could analyse to see where the problem is exactly, using gdb?

**Comment by apduvuri** [comment] 2024-06-04 12:24
No @dimitri , I am not sure we can get it.

**Comment by marikkan-microsoft** [comment] 2024-07-08 13:58
@apduvuri Was this issue encountered again? If not, we would have to close as "not reproducible".

**Comment by apduvuri** [comment] 2024-07-09 03:51
Hi @marikkan-microsoft , Yes as of now this issue is not encountered again.

**Comment by dimitri** [comment] 2024-07-16 13:31
Closing this issue for triage, please consider opening again with more information if needed.

**Closed by dimitri** 2024-07-16 13:31 UTC
Labels: bug
