### ISSUE TITLE
Cannot clone tables with identity/serial column

### ISSUE THREAD

**Issue by plvnv** [dimitri/pgcopydb#280] opened 2023-05-05 19:52 UTC
test scenario database
 
source `PostgresPro (standard) 11.15.1 on x86_64-pc-linux-gnu  `
destination `PostgresPro (standard) 13.10.1 on x86_64-pc-linux-gnu`

At the source:

```
create database test_db;
\c test_db
create table test_tbl (id bigint not null generated always as identity,text text);
\d
               List of relations
 Schema |      Name       |   Type   |  Owner   
--------+-----------------+----------+----------
 public | test_tbl        | table    | postgres
 public | test_tbl_id_seq | sequence | postgres
(2 rows)
```

Starting cloning 

`pgcopydb clone  --debug --restart`

or

`pgcopydb clone  --follow --debug --restart`

get the following error

```
22:38:16 10720 ERROR  pgsql.c:1536              [TARGET] ERROR:  relation "public.test_tbl_id_seq" does not exist
22:38:16 10720 ERROR  pgsql.c:1541              SQL query: select pg_catalog.setval(format('%I.%I', $1, $2), $3, $4)
22:38:16 10720 ERROR  pgsql.c:1542              SQL params: 'public', 'test_tbl_id_seq', '1', 'false'
22:38:16 10720 ERROR  schema.c:1904             Failed to set sequence "public"."test_tbl_id_seq" last value to 1
22:38:16 10720 ERROR  sequences.c:211           Failed to set sequence values for "public"."test_tbl_id_seq"
22:38:16 10722 SQL    pgsql.c:1501              [SOURCE] SET tcp_keepalives_idle TO '60s';
22:38:16 10720 SQL    pgsql.c:1501              [TARGET] rollback to savepoint sequences;
22:38:16 10711 NOTICE pgsql.c:1168              [SOURCE] Postgres version 11.15 (110015)
22:38:16 10711 SQL    pgsql.c:1501              [SOURCE] SET client_encoding TO 'UTF-8';
22:38:16 10722 SQL    pgsql.c:1501              [SOURCE] SET idle_in_transaction_session_timeout TO 0;
22:38:16 10720 SQL    pgsql.c:1501              [TARGET] savepoint sequences;
22:38:16 10711 SQL    pgsql.c:1501              [SOURCE] SET tcp_keepalives_idle TO '60s';
22:38:16 10720 SQL    pgsql.c:1501              [TARGET] select pg_catalog.setval(format('%I.%I', $1, $2), $3, $4);
22:38:16 10722 ERROR  file_utils.c:1069         BUG: sformat is called with a NULL target or format string
22:38:16 10720 SQL    pgsql.c:1505              'public', 'test_tbl_id_seq', '1', 'false'
22:38:16 10711 SQL    pgsql.c:1501              [SOURCE] SET idle_in_transaction_session_timeout TO 0;
22:38:16 10722 NOTICE table-data.c:833          (null)
22:38:16 10711 SQL    pgsql.c:512               Connecting to [target] "postgres://@localhost:7432/test_db?"
22:38:16 10722 SQL    pgsql.c:512               Connecting to [target] "postgres://@localhost:7432/test_db?"
22:38:16 10720 ERROR  pgsql.c:1536              [TARGET] ERROR:  relation "public.test_tbl_id_seq" does not exist
22:38:16 10720 ERROR  pgsql.c:1541              SQL query: select pg_catalog.setval(format('%I.%I', $1, $2), $3, $4)
22:38:16 10720 ERROR  pgsql.c:1542              SQL params: 'public', 'test_tbl_id_seq', '1', 'false'
22:38:16 10720 ERROR  schema.c:1904             Failed to set sequence "public"."test_tbl_id_seq" last value to 1
22:38:16 10720 ERROR  sequences.c:211           Failed to set sequence values for "public"."test_tbl_id_seq"
22:38:16 10720 SQL    pgsql.c:1501              [TARGET] rollback to savepoint sequences;
22:38:16 10720 SQL    pgsql.c:1501              [TARGET] COMMIT;
22:38:16 10720 SQL    pgsql.c:427               Disconnecting from [target] "postgres://@localhost:7432/test_db?"
22:38:16 10720 WARN   sequences.c:253           Failed to set values for 2 sequences, see above for details
22:38:16 10722 SQL    pgsql.c:1501              [TARGET] BEGIN;
22:38:16 10711 SQL    pgsql.c:1501              [TARGET] SET client_encoding TO 'UTF-8';
22:38:16 10722 SQL    pgsql.c:1501              [TARGET] TRUNCATE ONLY "public"."test_tbl";
22:38:16 10711 SQL    pgsql.c:1501              [TARGET] SET tcp_keepalives_idle TO '60s';
22:38:16 10711 SQL    pgsql.c:1501              [TARGET] SET maintenance_work_mem TO '1 GB';
22:38:16 10711 SQL    pgsql.c:1501              [TARGET] SET synchronous_commit TO 'off';
22:38:16 10711 SQL    pgsql.c:1501              [SOURCE] DECLARE bloboid CURSOR FOR SELECT oid FROM pg_largeobject_metadata ORDER BY 1;
22:38:16 10711 INFO   pgsql.c:2940              Copying large objects
22:38:16 10711 SQL    pgsql.c:1501              [SOURCE] FETCH 1000 IN bloboid;
22:38:16 10711 SQL    pgsql.c:1501              [SOURCE] COMMIT;
22:38:16 10711 SQL    pgsql.c:427               Disconnecting from [source] "postgres://@localhost:5432/test_db?"
22:38:16 10711 SQL    pgsql.c:427               Disconnecting from [target] "postgres://@localhost:7432/test_db?"
22:38:16 10722 SQL    pgsql.c:2279              copy "public"."test_tbl" to stdout;
22:38:16 10722 SQL    pgsql.c:2279              copy "public"."test_tbl" from stdin with (freeze);
22:38:16 10722 SQL    pgsql.c:1501              [TARGET] COMMIT;
22:38:16 10722 SQL    pgsql.c:427               Disconnecting from [target] "postgres://@localhost:7432/test_db?"
22:38:16 10722 DEBUG  table-data.c:659          Wrote summary for table "public"."test_tbl" at "/u03/tmp_sync/pgcopydb/run/tables/63276387.done"
22:38:16 10722 SQL    pgsql.c:1501              [SOURCE] COMMIT;
22:38:16 10722 SQL    pgsql.c:427               Disconnecting from [source] "postgres://@localhost:5432/test_db?"
22:38:16 10722 DEBUG  table-data.c:474          copydb_process_table_data_worker: done 1 copies, 0 errors
22:38:17 10721 DEBUG  copydb.c:1017             Sub-process 10722 exited with code 0
22:38:17 10721 DEBUG  copydb.c:992              copydb_wait_for_subprocesses: no more children
22:38:17 10701 INFO   table-data.c:142          COPY phase is done, now waiting for vacuum, index, blob, and sequences processes
22:38:17 10701 DEBUG  vacuum.c:275              Send STOP message to VACUUM queue 131119
22:38:17 10701 DEBUG  vacuum.c:275              Send STOP message to VACUUM queue 131119
22:38:17 10701 DEBUG  vacuum.c:275              Send STOP message to VACUUM queue 131119
22:38:17 10701 DEBUG  vacuum.c:275              Send STOP message to VACUUM queue 131119
22:38:17 10701 DEBUG  indexes.c:415             Send STOP message to CREATE INDEX queue 131120
22:38:17 10701 DEBUG  indexes.c:415             Send STOP message to CREATE INDEX queue 131120
22:38:17 10701 DEBUG  indexes.c:415             Send STOP message to CREATE INDEX queue 131120
22:38:17 10701 DEBUG  indexes.c:415             Send STOP message to CREATE INDEX queue 131120
22:38:17 10701 DEBUG  copydb.c:976              Waiting for sub-processes to finish
22:38:17 10701 DEBUG  copydb.c:1017             Sub-process 10711 exited with code 0
22:38:17 10701 ERROR  copydb.c:1024             Sub-process 10720 exited with code 12
22:38:17 10713 DEBUG  indexes.c:113             Stop message received by create index worker
22:38:17 10715 DEBUG  indexes.c:113             Stop message received by create index worker
22:38:17 10714 DEBUG  indexes.c:113             Stop message received by create index worker
22:38:17 10712 DEBUG  indexes.c:113             Stop message received by create index worker
22:38:17 10718 DEBUG  vacuum.c:116              Stop message received by vacuum worker
22:38:17 10717 DEBUG  vacuum.c:116              Stop message received by vacuum worker
22:38:17 10716 DEBUG  vacuum.c:116              Stop message received by vacuum worker
22:38:17 10719 DEBUG  vacuum.c:116              Stop message received by vacuum worker
22:38:17 10701 DEBUG  copydb.c:1017             Sub-process 10712 exited with code 0
22:38:17 10701 DEBUG  copydb.c:1017             Sub-process 10713 exited with code 0
22:38:17 10701 DEBUG  copydb.c:1017             Sub-process 10714 exited with code 0
22:38:17 10701 DEBUG  copydb.c:1017             Sub-process 10715 exited with code 0
22:38:17 10701 DEBUG  copydb.c:1017             Sub-process 10716 exited with code 0
22:38:17 10701 DEBUG  copydb.c:1017             Sub-process 10717 exited with code 0
22:38:17 10701 DEBUG  copydb.c:1017             Sub-process 10718 exited with code 0
22:38:17 10701 DEBUG  copydb.c:1017             Sub-process 10719 exited with code 0
22:38:17 10701 DEBUG  copydb.c:992              copydb_wait_for_subprocesses: no more children
22:38:17 10701 ERROR  table-data.c:164          Some sub-processes have exited with error status, see above for details
22:38:17 10701 ERROR  table-data.c:170          Errors detected, see above for details
22:38:17 10701 FATAL  table-data.c:55           Failed to COPY the data, see above for details
22:38:17 10701 ERROR  cli_clone_follow.c:430    Failed to clone source database, see above for details
22:38:17 10698 ERROR  cli_clone_follow.c:700    clone process 10701 has terminated [6]
22:38:17 10698 SQL    pgsql.c:1501              [SOURCE] COMMIT;
22:38:17 10698 SQL    pgsql.c:427               Disconnecting from [source] "postgres://@localhost:5432/test_db?"
22:38:17 10698 DEBUG  queue_utils.c:59          iprm -q 131120 (create index)
22:38:17 10698 DEBUG  queue_utils.c:59          iprm -q 131119 (vacuum)
22:38:17 10698 DEBUG  lock_utils.c:211          ipcrm -s 196664
22:38:17 10698 DEBUG  lock_utils.c:211          ipcrm -s 196663
22:38:17 10698 DEBUG  lock_utils.c:211          ipcrm -s 196662
```
```
pgcopydb --version
10:50:45 684 INFO   Running pgcopydb version 0.11.31.gc3ce5f4 from "/opt/pgpro/std-11/bin/pgcopydb"
pgcopydb version 0.11.31.gc3ce5f4
compiled with PostgreSQL 11.15 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
compatible with Postgres 10, 11, 12, 13, 14, and 15
```

**Comment by lospejos** [comment] 2023-05-07 14:52
This issue may be duplicate of/related to my issue I've created earlier. Check this:  #276

**Comment by dimitri** [comment] 2023-06-05 15:03
I failed to reproduce the issue, so I even added a unit test case about it. Closing now, I believe it's no longer an issue in the current codebase. Please consider opening again if needed.

**Comment by plvnv** [comment] 2023-06-06 10:05
With latest pgcopydb build 

```
 Running pgcopydb version 0.11.57.g090a1ca from "/opt/pgpro/std-11/bin/pgcopydb"
pgcopydb version 0.11.57.g090a1ca
compiled with PostgreSQL 11.15 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
compatible with Postgres 10, 11, 12, 13, 14, and 15
```

It reproduces only when add --filters option (no matter what you filtering inside exclude block)

```
export PGCOPYDB_SOURCE_PGURI="port=5432 host=localhost dbname=test_db"
export PGCOPYDB_TARGET_PGURI="port=7432 host=localhost dbname=test_db"


export TMPDIR=/u03/tmp_sync
export XDG_DATA_HOME=/u03/tmp_pgcopydb_follow_cdc

pgcopydb clone  --follow --verbose --restart --table-jobs 1 --index-jobs 1 --filters /home/postgres/pgcopydb.filter
```

without --filter  woks fine

 To reproduce bug, on source

```
create database test_db;
\c test_db
create table test_tbl (id bigint not null generated always as identity,text text);
create table test_tbl_2();
\d
               List of relations
 Schema |      Name       |   Type   |  Owner   
--------+-----------------+----------+----------
 public | test_tbl        | table    | postgres
 public | test_tbl_id_seq | sequence | postgres
 public | test_tbl_2      | table    | postgres
```


pgcopydb.filter

```
[exclude-table]
public.test_tbl_2
```
On target db

```
pgcopydb clone  --follow --verbose --restart --table-jobs 1 --index-jobs 1 --filters /home/postgres/pgcopydb.filter
```

Log file

[pgcopy_db_error_log_with_filter_option.log](https://github.com/dimitri/pgcopydb/files/11663156/pgcopy_db_error_log_with_filter_option.log)

**Comment by lospejos** [comment] 2023-06-06 12:03
I also still have this error.

**Comment by lospejos** [comment] 2023-06-07 14:25
@dimitri 
Me and @plvnv still have this issue so I reopen it if you wouldn't mind.

**Comment by dimitri** [comment] 2023-06-07 17:29
I believe I have a good work-in-progress patch. I have extended the tests for filtering to also test exclusion based filtering, and I could reproduce your issue there thanks to the detailed SQL resources etc that you shared. The tests are now passing. Can you test your own use-case with the branch `fix/schema-queries-for-dependencies-and-sequences` and report further difficulties or maybe success?

After that I will also need to review the other schema queries for exclusion filters, or add more to the testing to make sure all are exercised and checked properly.

**Closed** 2023-06-08 12:16 UTC
