### ISSUE TITLE
COPY command never finishes

### ISSUE THREAD

**Issue by djpenka** [dimitri/pgcopydb#876] opened 2024-08-27 20:06 UTC
I am performing a database migration from one Postgres 12 server to another Postgres 12 server using the following command:

`pgcopydb clone --skip-extensions --no-owner --restore-jobs=4 --table-jobs=4 --index-jobs=1 --trace --follow  `

This is being used to copy a database that has 495 tables, 16 million tuples, and approximately 8 GB of space on disk. When I do this, most of the database is copied over very rapidly, but the largest table (3019 MB) will never finish copying over. It locks a table, and the index jobs will eventually try to get a lock on the table but be unable to because the COPY command hasn't finished. Output related to the process handling copying the table is below, which was retrieved by grepping for the pid `171608`

```
2024-08-27 15:14:31.055 171608 TRACE table-data.c:867 copydb_copy_data_by_oid: 71640718 <EXPUNGED_SCHEMA.<EXPUNGED_TABLE> 0 0..0
2024-08-27 15:14:31.055 171608 DEBUG table-data.c:882 copydb_copy_data_by_oid: 71640718 <EXPUNGED_SCHEMA.<EXPUNGED_TABLE>, part 0
2024-08-27 15:14:31.055 171608 SQL pgsql.c:1568 [SOURCE 10900] select exists(          select 1            from pg_class c                 join pg_namespace n on n.oid = c.relnamespace           where c.oid = $1             and format('%I', n.nspname) = $2             and format('%I', c.relname) = $3       );
2024-08-27 15:14:31.055 171608 SQL pgsql.c:1581 [SOURCE 10900] '71640718', '<EXPUNGED_SCHEMA>', '<EXPUNGED_TABLE>'
2024-08-27 15:14:31.057 171608 SQL pgsql.c:2633 LOCK TABLE ONLY <EXPUNGED_SCHEMA.<EXPUNGED_TABLE> IN ACCESS SHARE MODE
2024-08-27 15:14:31.057 171608 SQL pgsql.c:1568 [SOURCE 10900] LOCK TABLE ONLY <EXPUNGED_SCHEMA.<EXPUNGED_TABLE> IN ACCESS SHARE MODE;
2024-08-27 15:14:31.058 171608 SQL pgsql.c:1568 [SOURCE 10900] select exists(          select 1            from pg_class c                 join pg_namespace n on n.oid = c.relnamespace           where c.oid = $1             and format('%I', n.nspname) = $2             and format('%I', c.relname) = $3       );
2024-08-27 15:14:31.058 171608 SQL pgsql.c:1581 [SOURCE 10900] '71640718', '<EXPUNGED_SCHEMA>', '<EXPUNGED_TABLE>'
2024-08-27 15:14:31.059 171608 SQLite catalog.c:7904 [SQLite]   select pid, start_time_epoch, done_time_epoch, duration,          bytes, command     from summary    where tableoid = $1 and partnum = $2
2024-08-27 15:14:31.059 171608 SQLite catalog.c:8283 [SQLite] 71640718, 0
2024-08-27 15:14:31.059 171608 SQLite catalog.c:7904 [SQLite]  select group_concat(attname order by attnum, ', ')        filter (where not attisgenerated)   from s_attr  where oid = $1
2024-08-27 15:14:31.059 171608 SQLite catalog.c:8283 [SQLite] 71640718
2024-08-27 15:14:31.059 171608 SQL pgsql.c:1568 [TARGET 26409] select has_table_privilege($1, $2);;
2024-08-27 15:14:31.059 171608 SQL pgsql.c:1581 [TARGET 26409] '<EXPUNGED_SCHEMA.<EXPUNGED_TABLE>', 'TRUNCATE'
2024-08-27 15:14:31.060 171608 SQLite catalog.c:7904 [SQLite] insert or replace into summary(pid, tableoid, partnum, start_time_epoch, command)values($1, $2, $3, $4, $5)
2024-08-27 15:14:31.060 171608 SQLite catalog.c:8283 [SQLite] 171608, 71640718, 0, 1724771671, COPY <EXPUNGED_SCHEMA.<EXPUNGED_TABLE>
2024-08-27 15:14:31.066 171608 SQLite catalog.c:7904 [SQLite] insert or replace into process(  pid, ps_type, ps_title, tableoid, partnum, indexoid)values($1, $2, $3, $4, $5, $6)
2024-08-27 15:14:31.066 171608 SQLite catalog.c:8283 [SQLite] 171608, COPY, pgcopydb: copy <EXPUNGED_SCHEMA.<EXPUNGED_TABLE>, 71640718, 0, 0
2024-08-27 15:14:31.072 171608 SQL pgsql.c:1568 [TARGET 26409] BEGIN;
2024-08-27 15:14:31.072 171608 NOTICE pgsql.c:2651 TRUNCATE ONLY <EXPUNGED_SCHEMA.<EXPUNGED_TABLE>
2024-08-27 15:14:31.072 171608 SQL pgsql.c:1568 [TARGET 26409] TRUNCATE ONLY <EXPUNGED_SCHEMA.<EXPUNGED_TABLE>;
2024-08-27 15:14:31.080 171608 NOTICE pgsql.c:2735 COPY <EXPUNGED_SCHEMA.<EXPUNGED_TABLE>
2024-08-27 15:14:31.080 171608 SQL pgsql.c:3145 copy (SELECT <EXPUNGED>...
2024-08-27 15:14:31.083 171608 SQL pgsql.c:3145 copy <EXPUNGED_SCHEMA.<EXPUNGED_TABLE>(<EXPUNGED_COLUMNS>) from stdin with (freeze);
2024-08-27 15:14:36.075 171608 SQLite catalog.c:7904 [SQLite] update summary set duration = $1, bytes = $2 where pid = $3 and tableoid = $4 and partnum = $5
2024-08-27 15:14:36.075 171608 SQLite catalog.c:8283 [SQLite] 5014, 82294130, 171608, 71640718, 0
2024-08-27 15:14:41.062 171608 SQLite catalog.c:7904 [SQLite] update summary set duration = $1, bytes = $2 where pid = $3 and tableoid = $4 and partnum = $5
2024-08-27 15:14:41.062 171608 SQLite catalog.c:8283 [SQLite] 10001, 152828184, 171608, 71640718, 0
2024-08-27 15:14:46.060 171608 SQLite catalog.c:7904 [SQLite] update summary set duration = $1, bytes = $2 where pid = $3 and tableoid = $4 and partnum = $5
2024-08-27 15:14:46.060 171608 SQLite catalog.c:8283 [SQLite] 15000, 190645729, 171608, 71640718, 0
2024-08-27 15:14:51.004 171608 SQLite catalog.c:7904 [SQLite] update summary set duration = $1, bytes = $2 where pid = $3 and tableoid = $4 and partnum = $5
2024-08-27 15:14:51.005 171608 SQLite catalog.c:8283 [SQLite] 19944, 257380633, 171608, 71640718, 0
```

This continues updating about every 5 seconds until the end, where it hangs and no longer has any output for this process. Additionally, the IO for the VM and databases drops significantly as the other COPY processes finish.

```
2024-08-27 15:18:11.012 171608 SQLite catalog.c:7904 [SQLite] update summary set duration = $1, bytes = $2 where pid = $3 and tableoid = $4 and partnum = $5
2024-08-27 15:18:11.012 171608 SQLite catalog.c:8283 [SQLite] 219951, 2599429115, 171608, 71640718, 0
2024-08-27 15:18:16.046 171608 SQLite catalog.c:7904 [SQLite] update summary set duration = $1, bytes = $2 where pid = $3 and tableoid = $4 and partnum = $5
2024-08-27 15:18:16.047 171608 SQLite catalog.c:8283 [SQLite] 224986, 2656975163, 171608, 71640718, 0
2024-08-27 15:18:21.007 171608 SQLite catalog.c:7904 [SQLite] update summary set duration = $1, bytes = $2 where pid = $3 and tableoid = $4 and partnum duration = $2 where pid = $3 and indexoid = $4
2024-08-27 15:18:21.007 171608 SQLite catalog.c:8283 [SQLite] 229945, 2740258466, 171608, 71640718, 0
2024-08-27 15:18:26.006 171608 SQLite catalog.c:7904 [SQLite] update summary set duration = $1, bytes = $2 where pid = $3 and tableoid = $4 and partnum = $5
2024-08-27 15:18:26.006 171608 SQLite catalog.c:8283 [SQLite] 234945, 2897515131, 171608, 71640718, 0
2024-08-27 18:55:18.418 171608 DEBUG pgsql.c:2873 Copy Stats Callback failed, see above for details
2024-08-27 18:55:18.419 171608 DEBUG pgsql.c:2763 COPY was asked to stop
2024-08-27 18:55:18.419 171608 ERROR table-data.c:785 Failed to copy data for table with oid 71640718 and part number 0, see above for details
```

At `2024-08-27 18:55:18.418` I interrupt the process and it exits.

What could be causing this to hang like this?

**Comment by djpenka** [comment] 2024-08-28 16:42
I manually ran the following steps again after restarting and updating everything on my VM. Copy finished quickly and was able to migrate all data. Not sure why the issue only crops up when indexes and data copying is performed simultaneously.

- pgcopydb snapshot &
- pgcopydb dump schema
- pgcopydb restore pre-data
- pgcopydb copy table-data
- pgcopydb copy blobs
- pgcopydb copy sequences
- pgcopydb copy indexes
- pgcopydb copy constraints
- pgcopydb restore post-data
- kill %1
-

**Comment by djpenka** [comment] 2024-08-28 17:34
Running `strace` on the process responsible for performing the copy, it appears to be caught in a semaphore

```
strace: Process 9102 attached
semtimedop(524292, [{sem_num=0, sem_op=-1, sem_flg=SEM_UNDO}], 1, NULL
```

**Comment by djpenka** [comment] 2024-09-04 13:26
I tried running the snapshot and follow commands in separate processes and only using `clone`. I was able to send a SIGINT when the deadlock was reached and resumed the steps manually. I was able to finish those steps with the `--resume` argument, but at the end I had differences in my table definitions, where a target table had a `UNIQUE INDEX` while the source had a `CONSTRAINT UNIQUE` on the same column.

**Comment by hanefi** [comment] 2024-09-04 13:48
Hi @djpenka,

This is the expected behavior as the system is waiting for an input from you to complete the migration.

Basically, pgcopydb is continues to monitor the changes on your source server to apply them in the target. You need to set and endpos value to let pgcopydb know that it is ok to stop logical replication after a particular lsn value.

See an example at https://pgcopydb.readthedocs.io/en/latest/ref/pgcopydb_clone.html#change-data-capture-example-1

Sorry for the late response as I missed this one.

**Comment by djpenka** [comment] 2024-09-04 14:11
No problem. I thought that initially too, however this hangs before the copy command and indexes are finished creating. Depending on the order of operations, there may be anywhere from 300 to 700 indexes waiting to be created according to `pgcopydb list progress` when the freeze happens. Additionally, `pgcopydb list progress --json` will show that the `COPY` command for the last large table no longer has network traffic flowing (`bytes-pretty` will no longer be increasing), and the indexes will be stuck. Based on `pg_stat_activity`, the `COPY` process is holding locks waiting on the client, and the index creation processes are waiting on the `COPY` process.

**Comment by cmdctl** [comment] 2024-09-04 15:42
having the same issue here.... the copy processes are left hanging... I have around 123 indexes non completed non in progress the command i use is the following:
```sh
pgcopydb clone \
  --table-jobs 4 \
  --index-jobs 4 \
  --drop-if-exists \
  --no-owner \
  --no-acl \
  --no-comments \
  --no-tablespaces \
  --restart \
  --source "$SOURCE_POSTGRES_URL/$db" \
  --target "$TARGET_POSTGRES_URL/$db"
  ```
  no change data capture with the `--follow` flag

**Comment by ldiqual** [comment] 2024-09-04 17:03
Same issue here with the following command on a brand new target database:

```
pgcopydb clone
  --source <source>
  --target <target>
  --no-owner
  --no-acl
  --trace
  --fail-fast
  --drop-if-exists
  --not-consistent
  --dir <dir>
```

Last 50 lines of trace: https://gist.github.com/ldiqual/d135c0a8c43b08ddd574c3d997978a25

`pgcopydb list progress` shows:

```
             |  Total Count |  In Progress |         Done
-------------+--------------+--------------+-------------
      Tables |          129 |            0 |            0
     Indexes |          487 |            0 |            0
```

Processes are hanging with no network change

<img width="1249" alt="image" src="https://github.com/user-attachments/assets/75d0badc-872c-4c42-a562-c74d842f80dc">

This occurs on 0.17 and the latest HEAD as well.

**Comment by cmdctl** [comment] 2024-09-05 06:50
I wonder if this is related #880

**Comment by cmdctl** [comment] 2024-09-05 11:04
tested again after #880 was merged and the issue seems to be resolved on my side. What i did was build the docker image from the latest HEAD and run the migrations through it. 🎉  Thank you!

**Comment by dimitri** [comment] 2024-09-05 11:53
Thanks @cmdctl for testing unreleased code and thanks @arajkumar for the fix. Closing the issue now!

**Closed by dimitri** 2024-09-05 11:53 UTC
