### ISSUE TITLE
Sequences creation is skipped and then follows the error:  relation "table_id_seq" does not exist

### ISSUE THREAD

**Issue by lospejos** [dimitri/pgcopydb#276] opened 2023-05-04 14:33 UTC
Built `pgcopydb` from sources, `main` branch, 2023-05-03 10:54:00UTC.

When we start data migration, we see error in logs:

```
ERROR  pgsql.c:1543              [TARGET] ERROR:  relation "sss.tbl_id_seq" does not exist
...
ERROR  schema.c:1948             Failed to set sequence "sss"."tbl_id_seq" last value to 2
```

Earlier in this log we see:

```
NOTICE dump_restore.c:386        Skipping filtered-out dumpId 780: SEQUENCE 243952 sss tbl_id_seq dbuser

NOTICE dump_restore.c:386        Skipping filtered-out dumpId 9578: SEQUENCE OWNED BY 0 sss tbl_id_seq dbuser
```

We see that in PR: #246 some changes was made regarding objects filtering etc.

Additionally, on our `source database` we reset ownership on all sequences to a one single user (schema owner, this is not the user used in connections for `pgcopydb`). This single user owns all objects in our schema, including tables, functions, types etc.

What sequences permission (or may be another conditions) should be set to meet requirements, to let all sequences not be filtered out during data migration process?

Any help will be appreciated.

**Comment by lospejos** [comment] 2023-05-08 12:01
We additionally checked previous version of `pgcopydb` on the same source database:

1) Checked out local repository copy to the latest commit before changes introduced in #246, it's a commit `187a89f`:
```
git checkout 187a89f
```
2)  Build `pgcopydb` and executed it (providing some additional `--no-comments` command line argument since it seems that this version has some issues filtering out schemas, it failed to set comments from extensions located in schemas that should be excluded via filters);

3) Data migration process finished successfully.

Based on this, we definitely assume that the changes introduced in #246 (namely SQL query added to filter sequences) breaks the data migration process.

**Comment by lospejos** [comment] 2023-05-16 09:53
Thanks for your reply.

Source database schema is here (actually you could create a single table with `id bigserial` column in the `custom schema`): 
[src_init.sql.txt](https://github.com/dimitri/pgcopydb/files/11486356/src_init.sql.txt).

Filter file `pgcopydb_vanilla_filter.ini` as well as other logs and `pgcopydb` files from `/tmp` are here:
[2023-05-16_12-41-40.zip](https://github.com/dimitri/pgcopydb/files/11486384/2023-05-16_12-41-40.zip)

Database migration started using command line:
```
pgcopydb clone --follow --table-jobs 4 --index-jobs 4 --restart --no-acl --no-owner --no-role-passwords --fail-fast --filter /opt/pgcopydb_vanilla_filter.ini --plugin wal2json --trace
```

**Comment by lospejos** [comment] 2023-06-03 17:28
Probably, if we do skip sequence object creation
```
NOTICE dump_restore.c:386        Skipping filtered-out dumpId 780: SEQUENCE 243952 sss tbl_id_seq dbuser
...
NOTICE dump_restore.c:386        Skipping filtered-out dumpId 9578: SEQUENCE OWNED BY 0 sss tbl_id_seq dbuser
```

we should also skip further setting values for columns where sequences are used, e.g. query

```
SQL query: select pg_catalog.setval(format('%I.%I', $1, $2), $3, $4)
SQL params: 'my_schema', 'my_table_id_seq', '1', 'false'
```

should not be executed.

**Comment by dimitri** [comment] 2023-06-05 09:15
Hi @lospejos ; the SQL query you're pasting comes from internal code of pgcopydb, it's not done by pg_restore. That's because pg_dump/pg_restore considers setting the sequences value to be part of the `--section data`; and we implement that section ourselves, only using `--section pre-data` and `--section post-data` from the Postgres tooling.

I will try to reproduce locally, I see that you shared a lot of information for me to dive into the issue. It seems strange to me that we manage to filter-out the sequence from the pg_restore activity but fail to skip it from the pgcopydb internal activities ; which would point out to a bug in the catalog queries maybe...

**Comment by dimitri** [comment] 2023-06-05 09:18
Ok I now see you're using this form of schema exclusion:

```
[exclude-schema]
public
```

And that might be all the hints I need to catch this bug. Looking at it now.

**Comment by dimitri** [comment] 2023-06-05 13:23
Please try again with current sources. I tried to reproduce with the files you've been sharing and with and without the `--follow` option, and failed to. Meaning for me it just works. Closing the issue for triage, please open again if it keeps failing for you, and in that case please provide useful information again for debug and repro.

First repro attempt:

```
$ pgcopydb clone --source "dbname=issue276" --target "dbname=issue276t"
15:19:43 24583 INFO   Running pgcopydb version 0.11.55.g5911755.dirty from "/Users/dim/dev/PostgreSQL/pgcopydb/src/bin/pgcopydb/pgcopydb"
15:19:43 24583 INFO   [SOURCE] Copying database from "postgres://@:/issue276?"
15:19:43 24583 INFO   [TARGET] Copying database into "postgres://@:/issue276t?"
15:19:43 24583 INFO   Exported snapshot "00000004-000001FE-1" from the source database
15:19:43 24587 INFO   STEP 1: dump the source database schema (pre/post data)
15:19:43 24587 INFO    /Applications/Postgres.app/Contents/Versions/12/bin/pg_dump -Fc --snapshot 00000004-000001FE-1 --section pre-data --file /var/folders/d7/zzxmgs9s16gdxxcm0hs0sssw0000gn/T//pgcopydb/schema/pre.dump 'postgres://@:/issue276?'
15:19:44 24587 INFO    /Applications/Postgres.app/Contents/Versions/12/bin/pg_dump -Fc --snapshot 00000004-000001FE-1 --section post-data --file /var/folders/d7/zzxmgs9s16gdxxcm0hs0sssw0000gn/T//pgcopydb/schema/post.dump 'postgres://@:/issue276?'
15:19:44 24587 INFO   STEP 2: fetch source database tables, indexes, and sequences
15:19:44 24587 INFO   Fetched information for 1 extensions
15:19:44 24587 INFO   Fetched information for 3 tables, with an estimated total of 0 tuples and 8192 B
15:19:44 24587 INFO   Fetched information for 6 indexes
15:19:44 24587 INFO   Fetching information for 3 sequences
15:19:44 24587 INFO   STEP 3: restore the pre-data section to the target database
15:19:44 24587 INFO    /Applications/Postgres.app/Contents/Versions/12/bin/pg_restore --dbname 'postgres://@:/issue276t?' --single-transaction --use-list /var/folders/d7/zzxmgs9s16gdxxcm0hs0sssw0000gn/T//pgcopydb/schema/pre.list /var/folders/d7/zzxmgs9s16gdxxcm0hs0sssw0000gn/T//pgcopydb/schema/pre.dump
15:19:44 24587 INFO   STEP 6: starting 4 CREATE INDEX processes
15:19:44 24587 INFO   STEP 7: constraints are built by the CREATE INDEX processes
15:19:44 24597 INFO   STEP 4: starting 3 table data COPY processes
15:19:44 24587 INFO   STEP 8: starting 4 VACUUM processes
15:19:44 24587 INFO   STEP 5: copy Large Objects (BLOBs) in 1 sub-process
15:19:44 24587 INFO   STEP 9: reset sequences values
15:19:44 24613 INFO   Reset sequences values on the target database
15:19:44 24611 INFO   Copying large objects
15:19:44 24587 INFO   STEP 10: restore the post-data section to the target database
15:19:44 24587 INFO    /Applications/Postgres.app/Contents/Versions/12/bin/pg_restore --dbname 'postgres://@:/issue276t?' --single-transaction --use-list /var/folders/d7/zzxmgs9s16gdxxcm0hs0sssw0000gn/T//pgcopydb/schema/post.list /var/folders/d7/zzxmgs9s16gdxxcm0hs0sssw0000gn/T//pgcopydb/schema/post.dump

   OID | Schema |       Name | copy duration | indexes | create index duration
-------+--------+------------+---------------+---------+----------------------
648262 |     s1 | tbl_status |          13ms |       2 |                  22ms
648273 |     s1 |       tbl1 |          10ms |       2 |                  36ms
648288 |     s1 |       tbl2 |           9ms |       2 |                  27ms


                                               Step   Connection    Duration   Concurrency
 --------------------------------------------------   ----------  ----------  ------------
                                        Dump Schema       source       322ms             1
   Catalog Queries (table ordering, filtering, etc)       source        30ms             1
                                     Prepare Schema       target        72ms             1
      COPY, INDEX, CONSTRAINTS, VACUUM (wall clock)         both       217ms         3 + 7
                                  COPY (cumulative)         both        32ms             3
                         Large Objects (cumulative)         both        19ms             1
             CREATE INDEX, CONSTRAINTS (cumulative)       target        85ms             4
                                    Finalize Schema       target        35ms             1
 --------------------------------------------------   ----------  ----------  ------------
                          Total Wall Clock Duration         both       678ms         3 + 7
 --------------------------------------------------   ----------  ----------  ------------
```

Second repro attempt:

```
$ pgcopydb stream cleanup
15:20:48 24717 INFO   Running pgcopydb version 0.11.55.g5911755.dirty from "/Users/dim/dev/PostgreSQL/pgcopydb/src/bin/pgcopydb/pgcopydb"
15:20:48 24717 INFO   Dropping replication slot "pgcopydb"
15:20:48 24717 WARN   NOTICE:  drop cascades to table pgcopydb.sentinel
15:20:48 24717 INFO   Dropping replication origin "pgcopydb"
~/dev/PostgreSQL/pgcopydb ./src/bin/pgcopydb/pgcopydb clone --source "dbname=issue276" --target "dbname=issue276t" --follow
15:20:50 24722 INFO   Running pgcopydb version 0.11.55.g5911755.dirty from "/Users/dim/dev/PostgreSQL/pgcopydb/src/bin/pgcopydb/pgcopydb"
15:20:50 24722 INFO   [SOURCE] Copying database from "postgres://@:/issue276?"
15:20:50 24722 INFO   [TARGET] Copying database into "postgres://@:/issue276t?"
15:20:50 24722 INFO   Created logical replication slot "pgcopydb" with plugin "test_decoding" at 6/3D56F3A8 and exported snapshot 00000004-0000022F-1
15:20:50 24722 INFO   create schema if not exists pgcopydb
15:20:50 24722 INFO   drop table if exists pgcopydb.sentinel
15:20:50 24722 WARN   NOTICE:  table "sentinel" does not exist, skipping
15:20:50 24722 INFO   create table pgcopydb.sentinel(startpos pg_lsn, endpos pg_lsn, apply bool,  write_lsn pg_lsn, flush_lsn pg_lsn, replay_lsn pg_lsn)
15:20:50 24722 INFO   Created logical replication origin "pgcopydb" at LSN 6/3D56F3A8
15:20:50 24728 INFO   STEP 1: dump the source database schema (pre/post data)
15:20:50 24728 INFO    /Applications/Postgres.app/Contents/Versions/12/bin/pg_dump -Fc --snapshot 00000004-0000022F-1 --section pre-data --file /var/folders/d7/zzxmgs9s16gdxxcm0hs0sssw0000gn/T//pgcopydb/schema/pre.dump 'postgres://@:/issue276?'
15:20:50 24732 INFO   Resuming streaming at LSN 6/3D56F3A8 from replication slot "pgcopydb"
15:20:50 24734 INFO   Waiting until the pgcopydb sentinel apply is enabled
15:20:51 24728 INFO    /Applications/Postgres.app/Contents/Versions/12/bin/pg_dump -Fc --snapshot 00000004-0000022F-1 --section post-data --file /var/folders/d7/zzxmgs9s16gdxxcm0hs0sssw0000gn/T//pgcopydb/schema/post.dump 'postgres://@:/issue276?'
15:20:51 24728 INFO   STEP 2: fetch source database tables, indexes, and sequences
15:20:51 24728 INFO   Fetched information for 1 extensions
15:20:51 24728 INFO   Fetched information for 3 tables, with an estimated total of 0 tuples and 8192 B
15:20:51 24728 INFO   Fetched information for 6 indexes
15:20:51 24728 INFO   Fetching information for 3 sequences
15:20:51 24728 INFO   STEP 3: restore the pre-data section to the target database
15:20:51 24728 INFO    /Applications/Postgres.app/Contents/Versions/12/bin/pg_restore --dbname 'postgres://@:/issue276t?' --single-transaction --use-list /var/folders/d7/zzxmgs9s16gdxxcm0hs0sssw0000gn/T//pgcopydb/schema/pre.list /var/folders/d7/zzxmgs9s16gdxxcm0hs0sssw0000gn/T//pgcopydb/schema/pre.dump
15:20:51 24728 INFO   STEP 6: starting 4 CREATE INDEX processes
15:20:51 24728 INFO   STEP 7: constraints are built by the CREATE INDEX processes
15:20:51 24749 INFO   STEP 4: starting 3 table data COPY processes
15:20:51 24728 INFO   STEP 8: starting 4 VACUUM processes
15:20:51 24728 INFO   STEP 5: copy Large Objects (BLOBs) in 1 sub-process
15:20:51 24728 INFO   STEP 9: reset sequences values
15:20:51 24765 INFO   Reset sequences values on the target database
15:20:51 24762 INFO   Copying large objects
15:20:51 24728 INFO   STEP 10: restore the post-data section to the target database
15:20:51 24728 INFO    /Applications/Postgres.app/Contents/Versions/12/bin/pg_restore --dbname 'postgres://@:/issue276t?' --single-transaction --use-list /var/folders/d7/zzxmgs9s16gdxxcm0hs0sssw0000gn/T//pgcopydb/schema/post.list /var/folders/d7/zzxmgs9s16gdxxcm0hs0sssw0000gn/T//pgcopydb/schema/post.dump
15:20:51 24728 INFO   Updating the pgcopydb.sentinel to enable applying changes

   OID | Schema |       Name | copy duration | indexes | create index duration
-------+--------+------------+---------------+---------+----------------------
648262 |     s1 | tbl_status |          41ms |       2 |                  26ms
648273 |     s1 |       tbl1 |          12ms |       2 |                  44ms
648288 |     s1 |       tbl2 |          10ms |       2 |                  43ms


                                               Step   Connection    Duration   Concurrency
 --------------------------------------------------   ----------  ----------  ------------
                                        Dump Schema       source       283ms             1
   Catalog Queries (table ordering, filtering, etc)       source        29ms             1
                                     Prepare Schema       target       262ms             1
      COPY, INDEX, CONSTRAINTS, VACUUM (wall clock)         both       217ms         3 + 7
                                  COPY (cumulative)         both        63ms             3
                         Large Objects (cumulative)         both        20ms             1
             CREATE INDEX, CONSTRAINTS (cumulative)       target       113ms             4
                                    Finalize Schema       target        50ms             1
 --------------------------------------------------   ----------  ----------  ------------
                          Total Wall Clock Duration         both       843ms         3 + 7
 --------------------------------------------------   ----------  ----------  ------------

15:20:52 24734 INFO   The pgcopydb sentinel has enabled applying changes
15:20:52 24734 INFO   Catching-up with changes from LSN 6/3D56F3A8
15:20:52 24734 INFO   File "/Users/dim/.local/share/pgcopydb/00000001000000060000003D.sql" does not exists yet, exit
15:20:52 24732 INFO   Reported write_lsn 6/3D5DD768, flush_lsn 6/3D5DD768, replay_lsn 0/0
15:20:52 24732 INFO   Streamed up to write_lsn 6/3D5DD768, flush_lsn 6/3D5DD768, stopping
15:20:52 24731 INFO   Subprocesses for prefetch, transform, and catchup have now all exited
15:20:52 24731 INFO   Current sentinel replay_lsn is 0/0
15:20:52 24731 INFO   Catching-up from existing on-disk files
15:20:52 24731 INFO   Transformed 2 JSON messages into SQL file "/Users/dim/.local/share/pgcopydb/00000001000000060000003D.sql"
15:20:52 24731 INFO   Catching-up with changes from LSN 6/3D56F3A8
15:20:52 24731 INFO   Replaying changes from file "/Users/dim/.local/share/pgcopydb/00000001000000060000003D.sql"
15:20:52 24731 INFO   Reached end of file "/Users/dim/.local/share/pgcopydb/00000001000000060000003D.sql" at 6/3D5DD768.
15:20:52 24731 INFO   Current sentinel replay_lsn is 6/3D5DD768
15:20:52 24731 INFO   Restarting logical decoding follower in replay mode
15:20:52 24798 INFO   Resuming streaming from latest file "/Users/dim/.local/share/pgcopydb/00000001000000060000003D.json"
15:20:52 24798 INFO   Resuming streaming at LSN 6/3D5DD768 from last message read in JSON file "/Users/dim/.local/share/pgcopydb/00000001000000060000003D.json", line 1
15:20:52 24800 INFO   Replaying changes from LSN 6/3D56F3A8
15:21:02 24798 INFO   Reported write_lsn 6/3D60A4A8, flush_lsn 0/0, replay_lsn 6/3D5DD810
15:21:13 24798 INFO   Reported write_lsn 6/3D62F710, flush_lsn 6/3D5DD960, replay_lsn 6/3D5DD810
15:21:24 24798 INFO   Reported write_lsn 6/3D631848, flush_lsn 6/3D60C5E0, replay_lsn 6/3D60C5E0
15:21:24 24798 INFO   Reported write_lsn 6/3D631810, flush_lsn 6/3D631810, replay_lsn 6/3D60C5E0
15:21:24 24798 INFO   Streamed up to write_lsn 6/3D631810, flush_lsn 6/3D631810, stopping
15:21:24 24800 INFO   Replayed up to replay_lsn 6/3D60C5E0, stopping
15:21:25 24731 INFO   Subprocesses for prefetch, transform, and catchup have now all exited
15:21:25 24731 INFO   Current sentinel replay_lsn is 6/3D631810, endpos has now been set to 6/3D631768
15:21:25 24731 INFO   Current endpos 6/3D631768 has been reached at 6/3D631810
15:21:25 24722 INFO   Fetching information for 3 sequences
15:21:25 24722 INFO   Reset sequences values on the target database
```

**Closed by dimitri** 2023-06-05 13:23 UTC
