### ISSUE TITLE
pgcopydb does not fail fast on error "*** stack smashing detected ***: terminated issue 

### ISSUE THREAD

**Issue by pranavidandu** [dimitri/pgcopydb#516] opened 2023-10-27 13:57 UTC
Stack smashing detected error during pgcopydb migration.
**Observations:**
Even after this error, I see that the remaining tables and indexes were copied. But after that, the post restore step did not start nor pgcopydb failed.
Discussed the same with Dimitri and we suspect it can be an issue in pgcopydb main process.
Attaching below few logs for reference. Please note that I have filtered out many logs in the between to focus on the important logs only. I have also masked server, db, table and index names. But following the timestamp will help in understanding when the issue was occurred and how the remaining tables and indexes  were copied after the issue

Logs:
<HTML><HEAD><TITLE>From Clipboard</TITLE></HEAD><BODY>

PreciseTimeStamp | MessageString
-- | --
2023-10-25 16:50:31.7890090 | *** stack smashing detected ***: terminated
2023-10-25 16:50:41.8749060 | *** stack smashing detected ***: terminated
2023-10-25 16:50:50.0358980 | *** stack smashing detected ***: terminated
2023-10-25 16:51:09.7125280 | *** stack smashing detected ***: terminated
2023-10-25 16:51:12.4393750 | Progress for database database1: Tables : total 162, completed 160, in-progress 2, in-queue 0, errored 0; Indexes: total 397, Completed 383, in-progress 0
2023-10-25 17:10:54.9175740 | 2023-10-25 17:10:54 62 NOTICE indexes.c:777             CREATE INDEX <***> ON <****> USING btree (***, ****);
2023-10-25 17:10:54.9175920 | 2023-10-25 17:10:54 62 SQL    pgsql.c:508               Connecting to [target] "postgres://****?sslmode=prefer&keepalives=1&keepalives_idle=10&keepalives_interval=10&keepalives_count=60"
2023-10-25 17:10:54.9231270 | 2023-10-25 17:10:54 63 NOTICE indexes.c:777             CREATE INDEX <***> ON <***> USING btree (***, ****);
2023-10-25 17:11:12.7765380 | Progress for database database1: Tables : total 162, completed 161, in-progress 1, in-queue 0, errored 0; Indexes: total 397, Completed 383, in-progress 4
2023-10-25 17:11:59.7907040 | 2023-10-25 17:11:59 64 SQL    pgsql.c:1492              [TARGET 12130] ALTER TABLE <***> ADD CONSTRAINT <***> PRIMARY KEY USING INDEX <***>;
2023-10-25 18:05:13.6623830 | Progress for database database1: Tables : total 162, completed 162, in-progress 0, in-queue 0, errored 0; Indexes: total 397, Completed 397, in-progress 0
</BODY></HTML>

**Comment by arajkumar** [comment] 2023-11-29 12:23
@pranavidandu Could you retest against master/main? There are couple of fixes merged recently to fix memory corruption. For example https://github.com/dimitri/pgcopydb/pull/534 moves allocation to heap to avoid stack corruption and https://github.com/dimitri/pgcopydb/pull/551 fixes the root cause.

**Comment by dimitri** [comment] 2023-12-27 07:44
Closing for triage. Consider opening again if that issue still needs attention, with more details if possible.

**Closed by dimitri** 2023-12-27 07:44 UTC
