### ISSUE TITLE
ERROR:  syntax error at or near ","

### ISSUE THREAD

**Issue by bck01215** [dimitri/pgcopydb#657] opened 2024-01-27 15:32 UTC
> LINE 1: copy (SELECT id, , name, icao, iata, faa_code, arff_certific..

I am getting extra commas generated in the select statement. 

Here is the command I ran
pgcopydb copy table-data \
>   --source "$SOURCE" \
>   --target "$TARGET" \
>   --snapshot $(cat /tmp/pgcopydb/snapshot) \
>   --split-tables-larger-than '10 GB'  \
>   --table-jobs 8

**Comment by VaibhaveS** [comment] 2024-01-28 06:40
Do you have a test case to reproduce?

**Comment by VaibhaveS** [comment] 2024-01-28 06:46
Not sure why we are seeing syntax errors being reported in COPY phase recently. #634

**Comment by pratikshetty1994** [comment] 2024-01-29 16:48
@bck01215 Getting similar issue.. 
16:42:42.373 20 NOTICE COPY public.tranlog
16:42:42.379 20 ERROR  [SOURCE 21424] [42601] ERROR:  syntax error at or near ","
16:42:42.379 20 ERROR  [SOURCE 21424] LINE 1: ...tionaldata, tags, visaitt, visatxnid, issuer_tax, , layer_of...
16:42:42.379 20 ERROR  [SOURCE 21424]                                                              ^
16:42:42.379 20 ERROR  [SOURCE 21424] Context: copy (SELECT id, deleted, localid, node, acquirer, mid, tid, stan, rrn, lifecycleindicator, lifecycletrace, lifecyclesequence, lifecycleauthtoken, ca_name, ca_city, ca_region, ca_country, ca_address, ca_postalcode, ca_phone, latitude, longitude, mcc, functioncode, reasoncode, filename, responsecode, approvalnumber, displaymessage, reversalcount, reversalid, completioncount, completionid, voidcount, voidid, date, transmissiondate, localtransactiondate, capturedate, settlementdate, batchnumber, itc, irc, originalitc, currencycode, amount, additionalamount, replacementamount, acquirerfee, issuerfee, returnedbalances, ss, ssdata, pdc, rc, extrc, duration, outstanding, request, response, refid, cardholder, card, account, account2, gltransaction, wallet, wallet2, additionaldata, tags, visaitt, visatxnid, issuer_tax, , layer_offset, settlementid, redeem_rewardslog, rewards_processed, value_date, plan_bundle_mapping_id, bill_ref_id, disputeref, instl_ref_id, updated_at, network_txn_id FROM ONLY public.tranlog) to stdout
16:42:42.379 20 ERROR  Failed to copy data for table with oid 4117045 and part number 0, see above for details

**Comment by MrVhek** [comment] 2024-01-30 08:15
```
2024-01-29 16:16:13.742 4645 ERROR  pgsql.c:2811              [SOURCE 15352] [42601] ERROR:  syntax error at or near ","
2024-01-29 16:16:13.742 4645 ERROR  pgsql.c:2819              [SOURCE 15352] LINE 1: ...ordexpire, admin, "needPasswordChange", lastseen, , , avatar...
2024-01-29 16:16:13.742 4645 ERROR  pgsql.c:2819              [SOURCE 15352]                                                              ^
2024-01-29 16:16:13.742 4645 ERROR  pgsql.c:2826              [SOURCE 15352] Context: copy (SELECT id, email, password, firstname, lastname, refreshtoken, resetpasswordtoken, resetpasswordexpire, admin, "needPasswordChange", lastseen, , , avatar, credits FROM ONLY public.users) to stdout
2024-01-29 16:16:13.742 4645 ERROR  table-data.c:777          Failed to copy data for table with oid 124325 and part number 0, see above for details
2024-01-29 16:16:13.742 4645 ERROR  pgsql.c:963               BUG: call to pgsql_commit() without holding an open multi statement connection
2024-01-29 16:16:13.742 4645 FATAL  snapshot.c:232            Failed to close snapshot "00000005-0028B3D5-1" on "(null)"
2024-01-29 16:16:16.074 4645 WARN   pgsql.c:856               WARNING:  there is already a transaction in progress
```

Same for me...

**Comment by dimitri** [comment] 2024-01-30 10:42
Hi,

Reading the code/loop that is responsible for preparing the column list for the COPY command I'm failing to see where the problem is, so the next candidate could be the SQLite catalogs. Could you run the following query, replacing the `'customer'` table name with the one that's problematic in your case in the logs, of course?

    sqlite3 ${TMPDIR}/pgcopydb/schema/source.db

```
sqlite> select a.* from s_attr a join s_table t on a.oid = t.oid where t.relname = 'customer' order by attnum;
oid     attnum  attypid  attname      attisprimary  attisgenerated
------  ------  -------  -----------  ------------  --------------
466622  1       23       customer_id  1             0             
466622  2       23       store_id     0             0             
466622  3       25       first_name   0             0             
466622  4       25       last_name    0             0             
466622  5       25       email        0             0             
466622  6       23       address_id   0             0             
466622  7       16       activebool   0             0             
466622  8       1082     create_date  0             0             
466622  9       1184     last_update  0             0             
466622  10      23       active       0             0             
```

Note that by default pgcopydb uses `/tmp` for the `${TMPDIR}`, you might also have been using `--dir`.

**Comment by pratikshetty1994** [comment] 2024-01-30 11:36
Hey @dimitri .. Here is the response in my case for the query you shared..Seems attnum 74 is missing.
4117045|1|20|id|1|0
4117045|2|1042|deleted|0|0
4117045|3|20|localid|0|0
4117045|4|1043|node|0|0
4117045|5|1043|acquirer|0|0
4117045|6|1043|mid|0|0
4117045|7|1043|tid|0|0
4117045|8|1042|stan|0|0
4117045|9|1043|rrn|0|0
4117045|10|1043|lifecycleindicator|0|0
4117045|11|1042|lifecycletrace|0|0
4117045|12|1043|lifecyclesequence|0|0
4117045|13|1043|lifecycleauthtoken|0|0
4117045|14|1043|ca_name|0|0
4117045|15|1043|ca_city|0|0
4117045|16|1043|ca_region|0|0
4117045|17|1043|ca_country|0|0
4117045|18|1043|ca_address|0|0
4117045|19|1043|ca_postalcode|0|0
4117045|20|1043|ca_phone|0|0
4117045|21|701|latitude|0|0
4117045|22|701|longitude|0|0
4117045|23|1043|mcc|0|0
4117045|24|1043|functioncode|0|0
4117045|25|1043|reasoncode|0|0
4117045|26|1043|filename|0|0
4117045|27|1043|responsecode|0|0
4117045|28|1043|approvalnumber|0|0
4117045|29|1043|displaymessage|0|0
4117045|30|23|reversalcount|0|0
4117045|31|20|reversalid|0|0
4117045|32|23|completioncount|0|0
4117045|33|20|completionid|0|0
4117045|34|23|voidcount|0|0
4117045|35|20|voidid|0|0
4117045|36|1114|date|0|0
4117045|37|1114|transmissiondate|0|0
4117045|38|1114|localtransactiondate|0|0
4117045|39|1082|capturedate|0|0
4117045|40|1082|settlementdate|0|0
4117045|41|20|batchnumber|0|0
4117045|42|1043|itc|0|0
4117045|43|1043|irc|0|0
4117045|44|1043|originalitc|0|0
4117045|45|1043|currencycode|0|0
4117045|46|1700|amount|0|0
4117045|47|1700|additionalamount|0|0
4117045|48|1700|replacementamount|0|0
4117045|49|1700|acquirerfee|0|0
4117045|50|1700|issuerfee|0|0
4117045|51|1043|returnedbalances|0|0
4117045|52|1043|ss|0|0
4117045|53|1043|ssdata|0|0
4117045|54|17|pdc|0|0
4117045|55|1043|rc|0|0
4117045|56|1043|extrc|0|0
4117045|57|23|duration|0|0
4117045|58|23|outstanding|0|0
4117045|59|17|request|0|0
4117045|60|17|response|0|0
4117045|61|20|refid|0|0
4117045|62|20|cardholder|0|0
4117045|63|20|card|0|0
4117045|64|20|account|0|0
4117045|65|20|account2|0|0
4117045|66|20|gltransaction|0|0
4117045|67|20|wallet|0|0
4117045|68|20|wallet2|0|0
4117045|69|1043|additionaldata|0|0
4117045|70|1043|tags|0|0
4117045|71|3802|visaitt|0|0
4117045|72|1043|visatxnid|0|0
4117045|73|1700|issuer_tax|0|0
4117045|75|23|layer_offset|0|0
4117045|76|20|settlementid|0|0
4117045|77|20|redeem_rewardslog|0|0
4117045|78|16|rewards_processed|0|0
4117045|79|1082|value_date|0|0
4117045|80|20|plan_bundle_mapping_id|0|0
4117045|81|20|bill_ref_id|0|0
4117045|82|20|disputeref|0|0
4117045|83|20|instl_ref_id|0|0
4117045|84|1114|updated_at|0|0
4117045|85|25|network_txn_id|0|0
4117045|86|20|itc_ref|0|0

**Comment by dimitri** [comment] 2024-02-05 15:05
Should be fixed in current version of pgcoydb in the “main” branch. Consider building from sources or using the Docker image built by the github CI system, per our documentation.

**Closed by dimitri** 2024-02-05 15:05 UTC

**Comment by bendem** [comment] 2024-07-17 13:11
Can confirm, this solved the problem for me. Do you have any idea why v0.16 is not getting into postgres repositories?

**Comment by dimitri** [comment] 2024-07-22 10:24
Well it seems to be listed at https://apt.postgresql.org/pub/repos/apt/pool/main/p/pgcopydb/ and also at https://packages.debian.org/search?keywords=pgcopydb.

**Comment by bendem** [comment] 2024-07-23 13:49
> Well it seems to be listed at https://apt.postgresql.org/pub/repos/apt/pool/main/p/pgcopydb/ and also at https://packages.debian.org/search?keywords=pgcopydb.

I was speaking about rhel : 
https://download.postgresql.org/pub/repos/yum/16/redhat/rhel-8-x86_64/
https://download.postgresql.org/pub/repos/yum/16/redhat/rhel-9-x86_64/

**Comment by dimitri** [comment] 2024-07-23 15:23
> I was speaking about rhel : https://download.postgresql.org/pub/repos/yum/16/redhat/rhel-8-x86_64/ https://download.postgresql.org/pub/repos/yum/16/redhat/rhel-9-x86_64/

Then let's ping @devrimgunduz as I don't know much about the RPM side of things.
