### ISSUE TITLE
Same table concurrency not kicking in

### ISSUE THREAD

**Issue by tomasz-sroka** [dimitri/pgcopydb#562] opened 2023-12-01 09:20 UTC
pgcopydb message:
```
INFO   Table "ma"."acg_soup" is 30 GB large, which is larger than --split-tables-larger-than 5120 MB, but does not have a unique column of type integer (int2/int4/int8).
WARN   Skipping same-table concurrency for table "ma"."acg_soup"
```
table definition:
```
\d ma.acg_soup
                                           Table "ma.acg_soup"
        Column        |            Type             | Collation | Nullable |           Default
----------------------+-----------------------------+-----------+----------+------------------------------
 coverage_id          | character varying(20)       |           | not null |
 stack                | character varying(12)       |           | not null |
[..]
 mig_id               | integer                     |           | not null | generated always as identity
Indexes:
    "acg_soup_pkey" PRIMARY KEY, btree (coverage_id, stack)
    "acg_soup_mig_id_key" UNIQUE CONSTRAINT, btree (mig_id)
```
pgcopydb version 0.10

The mig_id column was generated as shown below:
`ALTER TABLE ma.acg_soup ADD COLUMN mig_id INT4 GENERATED ALWAYS AS IDENTITY UNIQUE CONSTRAINT acg_soup_mig_id_key UNIQUE;`

**Comment by lospejos** [comment] 2023-12-01 10:23
Could you please explain why are you using outdated `0.10` version while there is a more recent `0.14` version does exist?

**Comment by tomasz-sroka** [comment] 2023-12-01 12:04
Hi Dimitri
It was the only one available in the distro I'm using.
I just switched to 0.13 but I hit the error reported here [#513](https://github.com/dimitri/pgcopydb/issues/513)
Trying now version 0.12 and so far it looks better.
Would you know where I could find rpm for version 0.14?

**Comment by tomasz-sroka** [comment] 2023-12-04 08:12
Hi Dimitri
I did test run over the weekend and as far as I could see the "split tables larger than" did not kick on for the table I mentioned in my first message.

**Comment by hanefi** [comment] 2023-12-06 14:21
I tried to reproduce this problem but I failed. My attempts below can be helpful to create a test case that can reproduce the issue. If we can reproduce the issue, we can be closer to fixing it.

I tried the steps below on v0.10 as well as latest main branch. I could not reproduce.

```sql
# Create a table without unique columns
CREATE TABLE test(
    id int,
    data int
);

# Add a generated identity using the command in the issue
ALTER TABLE test
    ADD COLUMN gen_id INT4 GENERATED ALWAYS AS IDENTITY UNIQUE CONSTRAINT test_gen_id UNIQUE;

# Populate with some fake data to test splits
INSERT INTO test(id, data)
SELECT
    x,x
FROM
    generate_series(1, 1000000) x;
```

You can see that we plan to split this table into 5 parts:

```bash
bash$ pgcopydb list table-parts --table-name=test --split-tables-larger-than=10MB
17:16:28 42583 INFO   Running pgcopydb version 0.13.38.g22e6544.dirty from "/home/hanefi/.pgenv/pgsql-15.1/bin/pgcopydb"
17:16:28 42583 INFO   Listing COPY partitions for table "public"."test" in "postgres://hanefi@localhost:9700/hanefi?"
17:16:28 42583 WARN   DEBUG:  parse <unnamed>:  with  t(min, max, parts) as  (    select min("id"), max("id"),           ceil(pg_table_size('public.test')::float / $1)      from "public"."test"  ),   ranges(n, parts, a, b) as   (     select n,            parts,            x as a,            coalesce((lead(x, 1) over(order by n)) - 1, max) as b       from t,            generate_series(min, max, ((max-min+1)/parts)::integer + 1)            with ordinality as s(x, n)   )    select n, parts, a, b, b-a+1 as count     from ranges order by n
17:16:28 42583 WARN   DEBUG:  bind <unnamed> to <unnamed>
17:16:28 42583 INFO   Table "public"."test" COPY will be split 5-ways
      Part |        Min |        Max |      Count
-----------+------------+------------+-----------
       1/5 |          1 |     200001 |     200001
       2/5 |     200002 |     400002 |     200001
       3/5 |     400003 |     600003 |     200001
       4/5 |     600004 |     800004 |     200001
       5/5 |     800005 |    1000000 |     199996
```

You can also see the summary table containing 5 lines for test table indicating that splits worked for this table.

```
bash$ pgcopydb clone --restart --split-tables-larger-than=10MB
....
  OID | Schema | Name | copy duration | indexes | create index duration
------+--------+------+---------------+---------+----------------------
49963 | public | test |         367ms |       1 |                 592ms
49963 | public | test |         331ms |       0 |                   0ms
49963 | public | test |         325ms |       0 |                   0ms
49963 | public | test |         343ms |       0 |                   0ms
49963 | public | test |         231ms |       0 |                   0ms
...
```

**Comment by tomasz-sroka** [comment] 2023-12-07 15:09
I believe that you found the problem. The source db was already copied once using pgcopydb and we had the pgcopydb schema created on the source database. Today I deleted pgcopydb schema on both source and target databases and the "split large tables" feature kicked in immediately. I've also noticed that it's using th CTID column which is great news.
Is it be possible that the pgcopydb schema on the source was the problem?

**Comment by hanefi** [comment] 2023-12-11 18:52
I went through all the SQL queries that try to find a candidate partition for `--split-tables-larger-than` parameter. I failed to reproduce the bug reported here. My guess is that the schema was missing some constraints when this problem happened. I suggest we close this issue and reopen if the issue happens in an environment that can reproduce this problem.

pgcopydb runs some sql commands on the source table to determine the column that will be used to split tables if their size are greater than a threshold value. This column should either have a primary key or a uniqueness constraint, and these queries seem to be running correctly.

Please reopen this issue if you are able to reproduce it in the future.

**Closed by hanefi** 2023-12-11 18:52 UTC
Labels: bug, good first issue
