### ISSUE TITLE
Option to exclude tables

### ISSUE THREAD

**Issue by maxstepanov** [dimitri/pgcopydb#2] opened 2022-01-16 14:09 UTC
Would be nice to be able to exclude some tables from being copied, like `pg_dump`'s option `--exclude-table-data`

PS. Nice work!

**Comment by dimitri** [comment] 2022-01-17 17:40
Duplicate of issue #4 ; closing this one here. Please join the discussion on issue #4.

**Closed by dimitri** 2022-01-17 17:40 UTC

**Comment by dimitri** [comment] 2022-05-10 12:26
I just merged support for filtering tables at #19 ; and the docs now have a full page for it at https://pgcopydb.readthedocs.io/en/latest/ref/pgcopydb_config.html.
